package com.night.ingale.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006E26)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6CFF82)
val md_theme_light_onPrimaryContainer = Color(0xFF002106)
val md_theme_light_secondary = Color(0xFF0D6E00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF00B331)
val md_theme_light_onSecondaryContainer = Color(0xFF012200)
val md_theme_light_tertiary = Color(0xFF486800)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEDFFCB)
val md_theme_light_onTertiaryContainer = Color(0xFF131F00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFDEFFE2)
val md_theme_light_onBackground = Color(0xFF026200)
val md_theme_light_surface = Color(0xFFF1FFF2)
val md_theme_light_onSurface = Color(0xFF002200)
val md_theme_light_surfaceVariant = Color(0xFFDEE5D9)
val md_theme_light_onSurfaceVariant = Color(0xFF424940)
val md_theme_light_outline = Color(0xFF72796F)
val md_theme_light_inverseOnSurface = Color(0xFFCAFFB9)
val md_theme_light_inverseSurface = Color(0xFF003A01)
val md_theme_light_inversePrimary = Color(0xFFB5FDBD)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006E26)
val md_theme_light_outlineVariant = Color(0xFF28A229)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF3AE362)
val md_theme_dark_onPrimary = Color(0xFF003910)
val md_theme_dark_primaryContainer = Color(0xFF00531B)
val md_theme_dark_onPrimaryContainer = Color(0xFF6CFF82)
val md_theme_dark_secondary = Color(0xFF56E23D)
val md_theme_dark_onSecondary = Color(0xFF043900)
val md_theme_dark_secondaryContainer = Color(0xFF12B100)
val md_theme_dark_onSecondaryContainer = Color(0xFF78FF5C)
val md_theme_dark_tertiary = Color(0xFFA0D832)
val md_theme_dark_onTertiary = Color(0xFF243600)
val md_theme_dark_tertiaryContainer = Color(0xFF354E00)
val md_theme_dark_onTertiaryContainer = Color(0xFFBBF54E)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001100)
val md_theme_dark_onBackground = Color(0xFFB0F49E)
val md_theme_dark_surface = Color(0xFF002E00)
val md_theme_dark_onSurface = Color(0xFFB0F49E)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C9BD)
val md_theme_dark_outline = Color(0xFF8C9388)
val md_theme_dark_inverseOnSurface = Color(0xFF002200)
val md_theme_dark_inverseSurface = Color(0xFFB0F49E)
val md_theme_dark_inversePrimary = Color(0xFF006E26)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF3AE362)
val md_theme_dark_outlineVariant = Color(0xFF005300)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF00CA4D)
